#!/usr/bin/env python

"""a quick script to filter audio files
"""

__author__ = "Reed Essick <reed.essick@kicp.uchicago.edu>"

#-------------------------------------------------

from scipy.io import wavfile
from scipy import signal

import numpy as np
import matplotlib
matplotlib.use("Agg")
from matplotlib import pyplot as plt

from argparse import ArgumentParser

#-------------------------------------------------

parser = ArgumentParser()

parser.add_argument('source', type=str)
parser.add_argument('target', type=str)

parser.add_argument('-v', '--verbose', default=False, action='store_true')

parser.add_argument('--tukey-alpha', default=0.1, type=float,
    help='the tukey alpha value used to generate window functions')

parser.add_argument('--lowpass', default=[], action='append', type=float, nargs=2,
    help="--lowpass rolloff_freq butterworth_order")
parser.add_argument('--highpass', default=[], action='append', type=float, nargs=2,
    help="--highpass rolloff_freq butterworth_order")

parser.add_argument('--whiten', default=None, type=str,
    help="read the PSD from this file and use it to whiten the input file")

parser.add_argument('-p', '--plot', default=False, action='store_true',
    help="generate a bunch of plots for this data")

args = parser.parse_args()

#-------------------------------------------------

raise NotImplementedError('WRITE ME \
read in signal (fs, data = wavfile.read(inpath))
read in PSD (if whitening)
apply filters
write out signal (wavfile.write(outpath, fs, transformed_data))')
