#!/usr/bin/env python

"""a quick script to estimate PSDs from a wav file
"""

__author__ = "Reed Essick <reed.essick@kicp.uchicago.edu>"

#-------------------------------------------------

from scipy.io import wavfile
from scipy import signal

import numpy as np
import matplotlib
matplotlib.use("Agg")
from matplotlib import pyplot as plt

from argparse import ArgumentParser

### non-standard libraries
import filters

#-------------------------------------------------

parser = ArgumentParser()

parser.add_argument('source', type=str)

parser.add_argument('-v', '--verbose', default=False, action='store_true')

parser.add_argument('--tukey-alpha', default=0.1, type=float,
    help='the tukey alpha value used to generate window functions')

parser.add_argument('--lowpass', default=[], action='append', type=float, nargs=2,
    help="--lowpass rolloff_freq butterworth_order")
parser.add_argument('--highpass', default=[], action='append', type=float, nargs=2,
    help="--highpass rolloff_freq butterworth_order")

parser.add_argument('-p', '--plot', default=False, action='store_true',
    help="generate a bunch of plots for this data")

args = parser.parse_args()
target = args.source[:-4]+'-psd.txt' ### write the PSD to an ascii file...

#-------------------------------------------------

raise NotImplementedError('WRITE ME! \
chunk up the data
FFT each chunk
apply filters
estimate PSD as an average')
